//! Hybrid scalar/NEON four-way `Keccak-f[1600]` backend for non-Apple
//! aarch64 cores.
//!
//! On Neoverse/Cortex cores before Cortex-X4 (and Graviton-class servers)
//! the SHA-3 instructions issue on a subset of the SIMD units, so a pure
//! NEON batched permutation leaves the scalar pipes idle. The kernel in
//! `keccak_x4_hybrid.s` advances states 0 and 1 in NEON (the two-way
//! `eor3`/`rax1`/`xar`/`bcax` selection) woven with states 2 and 3 in
//! general-purpose registers at two scalar rounds per vector round, one
//! scalar state per pass.
//!
//! The scalar rounds use lazy rotations: every rho rotation rides a
//! logical's free `ror`-operand under a stationary per-lane frame
//! assignment derived by CP-SAT with zero materialized rotates per steady
//! round — one fewer explicit `ror` per round than the hand-scheduled
//! kernels in the literature. Generated by `whittle emit keccak-x4-hybrid`;
//! Apple cores never dispatch here (see `build.rs`) because their SHA-3
//! instructions issue on all four SIMD units and the pure-NEON pairs win.

use core::arch::global_asm;

use super::scalar::ROUND_CONSTANTS;

global_asm!(include_str!("keccak_x4_hybrid.s"));

extern "C" {
    /// The generated kernel: `state` points to four sequential 25-lane
    /// states (100 `u64`s), `rc` to the 24 round constants.
    fn keccak_f1600_x4_hybrid(state: *mut u64, rc: *const u64);
}

/// Permutes four independent states at once: two in NEON, two in scalar
/// registers, in one interleaved kernel.
pub(crate) fn permute_x4(states: &mut [[u64; 25]; 4]) {
    // SAFETY: `states` is exactly the contiguous 100-u64 buffer the kernel
    // reads and writes; `sha3_selkie_hybrid` implies NEON + FEAT_SHA3.
    unsafe {
        keccak_f1600_x4_hybrid(states.as_mut_ptr().cast::<u64>(), ROUND_CONSTANTS.as_ptr());
    }
}
